// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// fxpower_cpp
List fxpower_cpp(int n1, int n2, double p1, double p2, double alpha, double eps);
RcppExport SEXP _zzfisher_fxpower_cpp(SEXP n1SEXP, SEXP n2SEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP alphaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fxpower_cpp(n1, n2, p1, p2, alpha, eps));
    return rcpp_result_gen;
END_RCPP
}
// cv_unequal_r
int cv_unequal_r(int n1, int n2, int r, double alpha);
RcppExport SEXP _zzfisher_cv_unequal_r(SEXP n1SEXP, SEXP n2SEXP, SEXP rSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(cv_unequal_r(n1, n2, r, alpha));
    return rcpp_result_gen;
END_RCPP
}
// xfmax_unequal_r
int xfmax_unequal_r(int n1, int n2, int r, double theta);
RcppExport SEXP _zzfisher_xfmax_unequal_r(SEXP n1SEXP, SEXP n2SEXP, SEXP rSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(xfmax_unequal_r(n1, n2, r, theta));
    return rcpp_result_gen;
END_RCPP
}
// binom_joint_r
double binom_joint_r(int n1, int n2, double p1, double p2, int x, int r);
RcppExport SEXP _zzfisher_binom_joint_r(SEXP n1SEXP, SEXP n2SEXP, SEXP p1SEXP, SEXP p2SEXP, SEXP xSEXP, SEXP rSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n1(n1SEXP);
    Rcpp::traits::input_parameter< int >::type n2(n2SEXP);
    Rcpp::traits::input_parameter< double >::type p1(p1SEXP);
    Rcpp::traits::input_parameter< double >::type p2(p2SEXP);
    Rcpp::traits::input_parameter< int >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    rcpp_result_gen = Rcpp::wrap(binom_joint_r(n1, n2, p1, p2, x, r));
    return rcpp_result_gen;
END_RCPP
}
// rx2_net_dp_cpp
double rx2_net_dp_cpp(IntegerMatrix dat);
RcppExport SEXP _zzfisher_rx2_net_dp_cpp(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_net_dp_cpp(dat));
    return rcpp_result_gen;
END_RCPP
}
// rx2_net_sweep_cpp
double rx2_net_sweep_cpp(IntegerMatrix dat, double eps_merge);
RcppExport SEXP _zzfisher_rx2_net_sweep_cpp(SEXP datSEXP, SEXP eps_mergeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    Rcpp::traits::input_parameter< double >::type eps_merge(eps_mergeSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_net_sweep_cpp(dat, eps_merge));
    return rcpp_result_gen;
END_RCPP
}
// rx2_net_vander_cpp
double rx2_net_vander_cpp(IntegerMatrix dat);
RcppExport SEXP _zzfisher_rx2_net_vander_cpp(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_net_vander_cpp(dat));
    return rcpp_result_gen;
END_RCPP
}
// rx2_tree_dp_cpp
double rx2_tree_dp_cpp(IntegerMatrix dat);
RcppExport SEXP _zzfisher_rx2_tree_dp_cpp(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_tree_dp_cpp(dat));
    return rcpp_result_gen;
END_RCPP
}
// rx2_tree_memo_c
double rx2_tree_memo_c(Rcpp::IntegerMatrix dat);
RcppExport SEXP _zzfisher_rx2_tree_memo_c(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_tree_memo_c(dat));
    return rcpp_result_gen;
END_RCPP
}
// rx2_tree_memo_cpp
double rx2_tree_memo_cpp(IntegerMatrix dat);
RcppExport SEXP _zzfisher_rx2_tree_memo_cpp(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_tree_memo_cpp(dat));
    return rcpp_result_gen;
END_RCPP
}
// rx2_tree_memo_profile
Rcpp::List rx2_tree_memo_profile(IntegerMatrix dat);
RcppExport SEXP _zzfisher_rx2_tree_memo_profile(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_tree_memo_profile(dat));
    return rcpp_result_gen;
END_RCPP
}
// rx2_tree_s4_c
double rx2_tree_s4_c(Rcpp::IntegerMatrix dat);
RcppExport SEXP _zzfisher_rx2_tree_s4_c(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rx2_tree_s4_c(dat));
    return rcpp_result_gen;
END_RCPP
}
// rxc_net_sweep_cpp
double rxc_net_sweep_cpp(IntegerMatrix dat_in);
RcppExport SEXP _zzfisher_rxc_net_sweep_cpp(SEXP dat_inSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat_in(dat_inSEXP);
    rcpp_result_gen = Rcpp::wrap(rxc_net_sweep_cpp(dat_in));
    return rcpp_result_gen;
END_RCPP
}
// rxc_tree_memo_cpp
double rxc_tree_memo_cpp(IntegerMatrix dat);
RcppExport SEXP _zzfisher_rxc_tree_memo_cpp(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerMatrix >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rxc_tree_memo_cpp(dat));
    return rcpp_result_gen;
END_RCPP
}
// rxck_net_ci_cpp
double rxck_net_ci_cpp(IntegerVector dat);
RcppExport SEXP _zzfisher_rxck_net_ci_cpp(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rxck_net_ci_cpp(dat));
    return rcpp_result_gen;
END_RCPP
}
// rxck_tree_memo_cpp
double rxck_tree_memo_cpp(IntegerVector dat);
RcppExport SEXP _zzfisher_rxck_tree_memo_cpp(SEXP datSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< IntegerVector >::type dat(datSEXP);
    rcpp_result_gen = Rcpp::wrap(rxck_tree_memo_cpp(dat));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_zzfisher_fxpower_cpp", (DL_FUNC) &_zzfisher_fxpower_cpp, 6},
    {"_zzfisher_cv_unequal_r", (DL_FUNC) &_zzfisher_cv_unequal_r, 4},
    {"_zzfisher_xfmax_unequal_r", (DL_FUNC) &_zzfisher_xfmax_unequal_r, 4},
    {"_zzfisher_binom_joint_r", (DL_FUNC) &_zzfisher_binom_joint_r, 6},
    {"_zzfisher_rx2_net_dp_cpp", (DL_FUNC) &_zzfisher_rx2_net_dp_cpp, 1},
    {"_zzfisher_rx2_net_sweep_cpp", (DL_FUNC) &_zzfisher_rx2_net_sweep_cpp, 2},
    {"_zzfisher_rx2_net_vander_cpp", (DL_FUNC) &_zzfisher_rx2_net_vander_cpp, 1},
    {"_zzfisher_rx2_tree_dp_cpp", (DL_FUNC) &_zzfisher_rx2_tree_dp_cpp, 1},
    {"_zzfisher_rx2_tree_memo_c", (DL_FUNC) &_zzfisher_rx2_tree_memo_c, 1},
    {"_zzfisher_rx2_tree_memo_cpp", (DL_FUNC) &_zzfisher_rx2_tree_memo_cpp, 1},
    {"_zzfisher_rx2_tree_memo_profile", (DL_FUNC) &_zzfisher_rx2_tree_memo_profile, 1},
    {"_zzfisher_rx2_tree_s4_c", (DL_FUNC) &_zzfisher_rx2_tree_s4_c, 1},
    {"_zzfisher_rxc_net_sweep_cpp", (DL_FUNC) &_zzfisher_rxc_net_sweep_cpp, 1},
    {"_zzfisher_rxc_tree_memo_cpp", (DL_FUNC) &_zzfisher_rxc_tree_memo_cpp, 1},
    {"_zzfisher_rxck_net_ci_cpp", (DL_FUNC) &_zzfisher_rxck_net_ci_cpp, 1},
    {"_zzfisher_rxck_tree_memo_cpp", (DL_FUNC) &_zzfisher_rxck_tree_memo_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_zzfisher(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
