# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.fxpower_cpp <- function(n1, n2, p1, p2, alpha, eps) {
    .Call(`_zzfisher_fxpower_cpp`, n1, n2, p1, p2, alpha, eps)
}

.cv_unequal_cpp <- function(n1, n2, r, alpha) {
    .Call(`_zzfisher_cv_unequal_r`, n1, n2, r, alpha)
}

.xfmax_unequal_cpp <- function(n1, n2, r, theta) {
    .Call(`_zzfisher_xfmax_unequal_r`, n1, n2, r, theta)
}

.binom_joint_cpp <- function(n1, n2, p1, p2, x, r) {
    .Call(`_zzfisher_binom_joint_r`, n1, n2, p1, p2, x, r)
}

.rx2_net_dp_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_net_dp_cpp`, dat)
}

.rx2_net_sweep_cpp <- function(dat, eps_merge = 1e-12) {
    .Call(`_zzfisher_rx2_net_sweep_cpp`, dat, eps_merge)
}

.rx2_net_vander_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_net_vander_cpp`, dat)
}

.rx2_tree_dp_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_tree_dp_cpp`, dat)
}

.rx2_tree_memo_c <- function(dat) {
    .Call(`_zzfisher_rx2_tree_memo_c`, dat)
}

.rx2_tree_memo_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_tree_memo_cpp`, dat)
}

.rx2_tree_memo_profile <- function(dat) {
    .Call(`_zzfisher_rx2_tree_memo_profile`, dat)
}

.rx2_tree_s4_c <- function(dat) {
    .Call(`_zzfisher_rx2_tree_s4_c`, dat)
}

.rxc_net_sweep_cpp <- function(dat_in) {
    .Call(`_zzfisher_rxc_net_sweep_cpp`, dat_in)
}

.rxc_tree_memo_cpp <- function(dat) {
    .Call(`_zzfisher_rxc_tree_memo_cpp`, dat)
}

.rxck_net_ci_cpp <- function(dat) {
    .Call(`_zzfisher_rxck_net_ci_cpp`, dat)
}

.rxck_tree_memo_cpp <- function(dat) {
    .Call(`_zzfisher_rxck_tree_memo_cpp`, dat)
}

