# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.net_dp_cpp <- function(dat) {
    .Call(`_zzfisher_net_dp_cpp`, dat)
}

.net_vander_cpp <- function(dat) {
    .Call(`_zzfisher_net_vander_cpp`, dat)
}

.tree_dp_cpp <- function(dat) {
    .Call(`_zzfisher_tree_dp_cpp`, dat)
}

.tree_memo_c <- function(dat) {
    .Call(`_zzfisher_tree_memo_c`, dat)
}

.tree_memo_cpp <- function(dat) {
    .Call(`_zzfisher_tree_memo_cpp`, dat)
}

.tree_memo_profile <- function(dat) {
    .Call(`_zzfisher_tree_memo_profile`, dat)
}

.tree_memo_s4_c <- function(dat) {
    .Call(`_zzfisher_tree_memo_s4_c`, dat)
}

