# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.rx2_net_dp_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_net_dp_cpp`, dat)
}

.rx2_net_vander_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_net_vander_cpp`, dat)
}

.rx2_tree_dp_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_tree_dp_cpp`, dat)
}

.rx2_tree_memo_c <- function(dat) {
    .Call(`_zzfisher_rx2_tree_memo_c`, dat)
}

.rx2_tree_memo_cpp <- function(dat) {
    .Call(`_zzfisher_rx2_tree_memo_cpp`, dat)
}

.rx2_tree_memo_profile <- function(dat) {
    .Call(`_zzfisher_rx2_tree_memo_profile`, dat)
}

.rx2_tree_s4_c <- function(dat) {
    .Call(`_zzfisher_rx2_tree_s4_c`, dat)
}

.rxc_tree_memo_cpp <- function(dat) {
    .Call(`_zzfisher_rxc_tree_memo_cpp`, dat)
}

.rxck_tree_memo_cpp <- function(dat) {
    .Call(`_zzfisher_rxck_tree_memo_cpp`, dat)
}

